server:
  port: 80
  contextPath: /icar-wechat/
spring:
  profiles.active: $profileActive$
  dubbo:
    application.name: icar-wechat
    scan: com.changan.icar.wechat.service.impl
    registry.address: zookeeper://111.231.205.136:2181
  view: 
    prefix: /WEB-INF/pages
    suffix: .jsp
wechat:
  token: 631424210205GQS
  aesKey: sxFzMor4LMmFnDmSFRPGzffvdAMsAqN3XIvbi9NQ4KB
  appSecret: c59a1fe79e3e23c19181ac7f88b2c0d8
  appId: wx75a0c8f0e32ae1cc
protocol: http
domain: icar.natapp1.cc