server:
  port: 9000
spring:
  profiles.active: $profileActive$
  dubbo:
    application.name: icar-wechat
    scan: com.changan.icar.wechat.service.impl
    registry.address: zookeeper://111.231.205.136:2181