buttons:
- name: 位置服务
  type: click
  key: location_service
  subButtons:
  - name: 我要接人
    type: click
    key: wyjr
    url: /icar-wechatmp/function/wyjr.do
  - name: 找人接我
    type: click
    key: zrjw
    url: /icar-wechatmp/function/zrjwSelectLocation.do
  - name: 快速导航
    type: location_select
    key: quick_navi
- name: 车辆控制
  type: click
  key: control_service
  subButtons:
  - name: 获取车辆位置
    type: view
    url: /icar-wechatmp/device/deviceLocation.do
    key: get_location
- name: 用户中心
  type: click
  subButtons:
  - name: 设备管理
    type: view
    url: /icar-wechatmp/device/deviceManage.do
    key: device_manage
  - name: 粉丝至上
    type: view
    url: /icar-wechatmp/function/privateOrdering.do
    key: private_ordering