server:
  contextPath: /icar-server/
spring:
  profiles.active: $profileActive$
  datasource:
    url: jdbc:mysql://111.231.205.136:3306/icar?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: aass7788
    driver-class-name: com.mysql.jdbc.Driver
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
mybatis:
  typeAliasesPackage: com.changan.icar.comm.po
  mapperLocations: classpath:mapper/*.xml
jpush:
  masterSecret: 602088caedef4e73d19d3052
  appKey: 1a35780231b11f6e558e3e16